<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWC6X4b1\AdminKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWC6X4b1/AdminKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWC6X4b1.legacy');

    return;
}

if (!\class_exists(AdminKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWC6X4b1\AdminKernelDevDebugContainer::class, AdminKernelDevDebugContainer::class, false);
}

return new \ContainerWC6X4b1\AdminKernelDevDebugContainer([
    'container.build_hash' => 'WC6X4b1',
    'container.build_id' => '5160ff80',
    'container.build_time' => 1758729865,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWC6X4b1');
